### ISSUE TITLE
KT epg 한글 깨짐 건

### ISSUE THREAD

**Issue by ohnggni** [wiserain/epg2xml#3]
최신버젼의 python EPG를 사용한 이후로 다음과 같은 EPG 깨짐 증상이 발생합니다.
아래는 Channel.JSON파일로 제가 임의로 KT것으로 수정한 것입니다. 
스크린샷 중 특정채널 ebs english, plus1/2, 뽀요TV, 캐리TV, Smile TV 등만 글씨가 깨지고 있습니다.

{ "Id": 56, "Name": "EBS English", "KT Name": "EBS English", "KTCh": 973, "LG Name": "EBS English", "LGCh": 162, "SK Name": "EBS English", "SKCh": 202, "Radio Name": "", "RadioCh": null, "Icon_url": "http://i.imgur.com/Rx4mgpm.png", "Source": "KT", "ServiceId": "973" },
{ "Id": 58, "Name": "EBS PLUS1", "KT Name": "EBS PLUS1", "KTCh": 157, "LG Name": "EBS+1", "LGCh": 163, "SK Name": "EBS +1", "SKCh": 203, "Radio Name": "", "RadioCh": null, "Icon_url": "http://i.imgur.com/WGlWiWy.png", "Source": "KT", "ServiceId": "972" },
{ "Id": 59, "Name": "EBS PLUS2", "KT Name": "EBS PLUS2", "KTCh": 158, "LG Name": "EBS+2", "LGCh": 164, "SK Name": "EBS +2", "SKCh": 204, "Radio Name": "", "RadioCh": null, "Icon_url": "http://i.imgur.com/QPq2wcg.png", "Source": "KT", "ServiceId": "971" },
{ "Id": 182, "Name": "Smile TV", "KT Name": "Smile TV", "KTCh": 84, "LG Name": "", "LGCh": null, "SK Name": "", "SKCh": null, "Radio Name": "", "RadioCh": null, "Icon_url": "http://i.imgur.com/alk8plD.png", "Source": "KT", "ServiceId": "84" },
{ "Id": 495, "Name": "뽀요TV", "KT Name": "뽀요TV", "KTCh": 976, "LG Name": "", "LGCh": null, "SK Name": "", "SKCh": null, "Radio Name": "", "RadioCh": null, "Icon_url": "https://tvlogo/뽀요TV.png", "Source": "KT", "ServiceId": "976" },
{ "Id": 496, "Name": "캐리TV", "KT Name": "캐리TV", "KTCh": 985, "LG Name": "", "LGCh": null, "SK Name": "", "SKCh": null, "Radio Name": "", "RadioCh": null, "Icon_url": "https://tvlogo/캐리TV.png", "Source": "KT", "ServiceId": "985" },
{ "Id": 497, "Name": "핑크퐁채널", "KT Name": "핑크퐁채널", "KTCh": 988, "LG Name": "", "LGCh": null, "SK Name": "", "SKCh": null, "Radio Name": "", "RadioCh": null, "Icon_url": "https://tv.kt.com/relatedmaterial/ch_logo/live/7e6dfc0d80502185754.png", "Source": "KT", "ServiceId": "988" },
{ "Id": 498, "Name": "대교상상kids", "KT Name": "대교상상kids", "KTCh": 981, "LG Name": "", "LGCh": null, "SK Name": "", "SKCh": null, "Radio Name": "", "RadioCh": null, "Icon_url": "https://tv.kt.com/relatedmaterial/ch_logo/live/63cdb05180502185807.png", "Source": "KT", "ServiceId": "981" },
<img width="1322" alt="스크린샷 2020-03-30 오후 5 30 58" src="https://user-images.githubusercontent.com/33609687/77891848-92bca780-72ac-11ea-9817-c38f490f9331.png">
<img width="1353" alt="스크린샷 2020-03-30 오후 5 32 49" src="https://user-images.githubusercontent.com/33609687/77891857-96e8c500-72ac-11ea-9432-db14042bd5bf.png">

확인 부탁드립니다~~

**Comment by wiserain** [comment]
@ohnggni 확인했는데 문제가 없네요. python3가 맞는지 버전이 1.2.9 최신버전이 맞는지 확인하시고 그래도 문제가 있으면 xml 파일로 떠서 알려주세요.

**Comment by ohnggni** [comment]
@wiserain docker 터미널 들어가서 확인해보니 python 3.8.2이고, epg2xml.py 파일은 1.2.9입니다. 일부 채널을 KT->SK로 바꾸니 또 잘 나옵니다. 최근에 1.2.6p1 에서 1.2.9로 업데이트 하고 나서 생긴 문제는 맞습니다.
왠지 KT만 뭔가 안되는 것 같은데, 도통 모르겠네요.

xml파일경로는 http://.me/xmltv.xml 이며, KT라 앞쪽이라, line 509부터 깨진 글자들을 보실 수 있습니다.

**Comment by wiserain** [comment]
@ohnggni 링크 주신거 제가 받은 xml에 509 라인은 ```  <channel id="500">```입니다. 다른 글자 깨진것도 못 찾겠고, epg 날짜도 20190225로 1주일쯤 전이네요.

**Comment by ohnggni** [comment]
@wiserain 죄송합니다. 파일을 잘못된 위치에 복사했었네요. 어쨌든 지금은 아래 링크에서 다운로드 하시면, 문제가 보이는 xmltv.xml파일을 보실 수 있습니다.
http://.me/xmltv.xml

번거롭지만 다시한번 부탁드립니다.

**Comment by wiserain** [comment]
@ohnggni 재현이 안되는데 환경을 알려주세요. 네이티브(리눅스,윈도우)/도커 여부, python 패키지(requests, Beautifulsoup) 버전. 아니면 접속해서 테스트하게 해주세요.

**Comment by ohnggni** [comment]
@wiserain 환경은 다음과 같습니다.

Synology DS716+ / Docker 이치로님 tvheadend:latest로 설치
--> 최근에 컨테이너 삭제하고 재설치했습니다.

Python 패키지는 아래와 같습니다.
root@tvh1:/epg2xml# pip3 list
Package        Version  
-------------- ---------
beautifulsoup4 4.8.1    
certifi        2019.9.11
chardet        3.0.4    
idna           2.8      
lxml           4.4.2    
pip            19.2.3   
requests       2.22.0   
setuptools     41.2.0   
soupsieve      1.9.5    
urllib3        1.25.7

**Comment by wiserain** [comment]
도커에서는 안해봤군요. 확인했고 수정했습니다.

**Comment by ohnggni** [comment]
@wiserain 수정파일로 다시 돌려보니, 잘 됩니다~!!! 감사합니다 😄
