### ISSUE TITLE
NAVER EPG 프로그램명에 회차정보 표시 기능 추가 부탁립니다.

### ISSUE THREAD

**Issue by zmdk0913** [wiserain/epg2xml#5]
나머지 EPG들은 제목에 회차표시 기능이 잘 작동하는데 NAVER EPG는 회차표시가 되지 않습니다. 기능 개선 부탁드립니다. 감사합니다.

**Comment by wiserain** [comment]
https://m.search.naver.com/search.naver?where=m&query=%ED%8E%B8%EC%84%B1%ED%91%9C 네이버 편성표에 회차 정보가 없어서 다른 방법이 없습니다.

**Comment by zmdk0913** [comment]
![Screenshot_20200607-210834_Chrome](https://user-images.githubusercontent.com/19605115/83968296-2e990e00-a903-11ea-8d1c-09814036b848.jpg)
kbs world는 또 다르네요

**Comment by zmdk0913** [comment]
![Screenshot_20200607-210829_Chrome](https://user-images.githubusercontent.com/19605115/83968314-51c3bd80-a903-11ea-96e4-9d414074fabb.jpg)
일부는 회차정보 나옵니다

**Comment by wiserain** [comment]
모바일 페이지에서는 회차 없이 보여주는군요. 데스크탑 페이지는 괜찮고... 수정할게요. 파이썬 버전만 적용될겁니다.

**Comment by zmdk0913** [comment]
넵 파이썬으로 사용해서 문제없겠네요. 반영 감사드립니다

**Comment by wiserain** [comment]
모바일 페이지 말고는 serviceid로 편성표를 주는 url을 알 수가 없네요. 데스크탑 페이지에서는 내부적으로 스크립트써서 가져오는 것 같은데 방법을 모르겠습니다. 관련 API를 알려주시면 다시 보겠습니다.
