### ISSUE TITLE
SK btv 사이트 변경

### ISSUE THREAD

**Issue by wiserain** [wiserain/epg2xml#6]
더이상 해당 주소로는 서비스하지 않는듯하다. 모바일 앱에서 편성표를 보여주는데 api 주소는 알아냈지만 하루 밖에 안 주는듯 하다. 흠...

하루도 아니고 현시점을 기준으로 당일 예정 방송만 보여준다.

**Comment by dlengmlek** [comment]
수고많으십니다. 

안그래도 어제 부터 이상해서 들어와보니 역시 그런거군요.

**Comment by wiserain** [comment]
일단은 다른 소스로 돌려 쓰세요.

**Comment by dlengmlek** [comment]
티빙해보니 파이썬 에러가 생기는데 ... 

2020/09/04 03:53:25 INFO     655 소스가 TVING인 채널을 가져오고 있습니다.
Traceback (most recent call last):
  File "/root/epg2xml/epg2xml.py", line 1198, in <module>
    getEpg()
  File "/root/epg2xml/epg2xml.py", line 137, in getEpg
    GetEPGFromTVING([c for c in Channeldatajson if c['Source'] == 'TVING'])
  File "/root/epg2xml/epg2xml.py", line 757, in GetEPGFromTVING
    for ch in get_json(params):
  File "/root/epg2xml/epg2xml.py", line 690, in get_json
    raise requests.exceptions.RequestException
requests.exceptions.RequestException

이렇게 검색하다 중단이 됩니다.

**Comment by wiserain** [comment]
> 
> 
> 티빙해보니 파이썬 에러가 생기는데 ...
> 
> 2020/09/04 03:53:25 INFO 655 소스가 TVING인 채널을 가져오고 있습니다.
> Traceback (most recent call last):
> File "/root/epg2xml/epg2xml.py", line 1198, in
> getEpg()
> File "/root/epg2xml/epg2xml.py", line 137, in getEpg
> GetEPGFromTVING([c for c in Channeldatajson if c['Source'] == 'TVING'])
> File "/root/epg2xml/epg2xml.py", line 757, in GetEPGFromTVING
> for ch in get_json(params):
> File "/root/epg2xml/epg2xml.py", line 690, in get_json
> raise requests.exceptions.RequestException
> requests.exceptions.RequestException
> 
> 이렇게 검색하다 중단이 됩니다.

@dlengmlek 방금 확인했는데 잘 됩니다. 실제 방송이 없는 새벽시간에는 안될 수도 있습니다. 여전히 안된다면 요청한 채널의 서비스 아이디를 포함해서 새로 이슈를 오픈해 주세요.

**Comment by mintmocha05** [comment]
컴퓨터 날짜를 내일로 바꾸고 사이트 들어가보면 그 시간에 맞는 편성표 하나씩은 나오는데 하루 전체로는 안나오네요.
http://mobilebtv.com:8080/view/v3.0/epg

**Comment by wiserain** [comment]
@mintmocha05 네 제공을 하는지, 파라미터나 방법은 뭔지 브라우저 도구로는 모르겠네요. 아시는 분은 제보 부탁드립니다. 일단은 1.5.0에서 막아뒀습니다.
