### ISSUE TITLE
잘 쓰고 있습니다! 그런데 파이썬3로 넘어오면서 lxml 모듈 인식을 못하네요

### ISSUE THREAD

**Issue by mmxdog** [wiserain/epg2xml#8]
시놀로지에 패키지로 tvheadend 설치해서 파이썬3 패키지 설치 후 파이썬 모듈도 설치하고
파이썬3용 pip 새로 인스톨하고, 뷰티풀소프4 설치하고, requests 설치하고, lxml 설치하려하는데 lxml이 설치가 안되네요
이게 libxml2랑 libxslt 여기서 호환이 안되서 lxml 설치가 안되는것 같은데 시놀로지 쓰다보니 apt-get install로 저 2개가 업데이트 나 설치가 안되네요.

이것저것 하는 방법이 있긴한데 너무 복잡해서 이걸 설치해말아 고민만하다 어찌어찌
WARNING  084 lxml 모듈이 설치되지 않아 html.parser로 동작합니다. 속도가 느립니다.
이렇게 되면서 일단 xml파일로 생성은 되기때문에 쓰고는 있습니다.

좋은 방법 없을까요?
어쨌든 잘 쓰고 있습니다 ㅎㅎ 고맙습니다.

**Comment by wiserain** [comment]
어... 전 시놀로지에서 설치 잘 됩니다.

```bash
user@synology:~/epg2xml$ sudo python3 -m pip install lxml
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting lxml
  Downloading lxml-4.5.2-cp35-cp35m-manylinux1_x86_64.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 923 kB/s 
Installing collected packages: lxml
Successfully installed lxml-4.5.2
```

그 이후로 epg2xml.py에서 인식해서 빠르게 잘 돌아가구요. 다시 한번 점검해보세요.

**Comment by mmxdog** [comment]
> 어... 전 시놀로지에서 설치 잘 됩니다.
> 
> ```shell
> user@synology:~/epg2xml$ sudo python3 -m pip install lxml
> DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
> Collecting lxml
>   Downloading lxml-4.5.2-cp35-cp35m-manylinux1_x86_64.whl (5.5 MB)
>      |████████████████████████████████| 5.5 MB 923 kB/s 
> Installing collected packages: lxml
> Successfully installed lxml-4.5.2
> ```
> 
> 그 이후로 epg2xml.py에서 인식해서 빠르게 잘 돌아가구요. 다시 한번 점검해보세요.

답변 고맙습니다.  댓글 달아주신거 보니까 x86 시스템이시네요.
전 ARM이라 안되는듯합니다.

/#epg2xml$ sudo python3 -m pip install lxml
Collecting lxml
  Using cached lxml-4.5.2.tar.gz (4.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.a                      rgv[0] = '"'"'/tmp/pip-install-onb6he3_/lxml/setup.py'"'"'; __file__='"'"'/tmp/p                      ip-install-onb6he3_/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)                      (__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(co                      mpile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-inf                      o-c31vu5go
         cwd: /tmp/pip-install-onb6he3_/lxml/
    Complete output (3 lines):
    Building lxml version 4.5.2.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are ins                      talled.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th                      e logs for full command output.

이런 메시지가 뜨고 안되네요 ㅠㅠ
어쨌든 고맙습니다 ^^

**Comment by wiserain** [comment]
python pre-compiled wheel로 설치해보시는건 어떨까 싶네요. 아니면 optware나 entware 깔고 직접 빌드해서 설치하시는 수 밖에 없습니다.
