### ISSUE TITLE
SKB EPG에 장르구분 나오도록 부탁 드립니다.

### ISSUE THREAD

**Issue by novarova** [wiserain/epg2xml#9]
안녕하세요. 항상 감사드리며 사용하고 있습니다.

일전에 SK EPG 가능할 때에 각 채널별 장르가 구분되도록 수정을 해 주셨었는데요... 이번에 SKB만 가능하게 되면서 소스변경을 해 봤더니 장르가 구분되어 나오지 않더라구요... ㅠ.ㅠ 번거로우시겠지만 시간 되시는대로 SKB에서도 장르구분이 가능하도록 변경해 주시면 감사하겠습니다.

감사합니다~

**Comment by wiserain** [comment]
사이트에서 장르 정보를 주지 않아서 불가능합니다. 가능한 방법 있으면 알려주세요.

**Comment by novarova** [comment]
> 사이트에서 장르 정보를 주지 않아서 불가능합니다. 가능한 방법 있으면 알려주세요.

아... 그렇군요. 아쉽네요. 답변 감사합니다.

**Comment by wiserain** [comment]
질문. 채널 장르인가요? 프로그램 별 장르인가요?

**Comment by novarova** [comment]
> 질문. 채널 장르인가요? 프로그램 별 장르인가요?

프로그램 별 장르입니다. 이전 SK EPG도 프로그램별 장르로 수정해 주셨었습니다.

**Comment by wiserain** [comment]
네 기억나네요. SK가 정보를 참 많이 줬습니다. SKB는 그런게 없네요. 혹시 방법을 아시는 분은 알려주세요.
